version: '3'

services:
  frontend:
    image: elfergouchyassine/mern-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/mern-app/certbot/conf:/etc/letsencrypt
      - ~/mern-app/certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: elfergouchyassine/mern-backend:latest
    expose:
      - "8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge